CLEARANCES = {
    "C": "Confidential",
    "S": "Secret",
    "TS": "Top Secret",
    "TS/SCI": "Top Secret / Sensitive Compartmented Information",
    "TS/SCI w/ CI Poly": "Top Secret / Sensitive Compartmented Information with Counterintelligence Polygraph",
    "TS/SCI w/ FS Poly": "Top Secret / Sensitive Compartmented Information with Full Scope Polygraph",
}

# source: https://www.defense.gov/Resources/Insignia/
ENLISTED_PAYGRADES = {
    "E-1": {
        "Army": ["Private"],
        "Marine Corps": ["Private"],
        "Navy": ["Seaman Recruit"],
        "Air Force": ["Airman Basic"],
        "Space Force": ["Specialist 1"],
    },
    "E-2": {
        "Army": ["Private"],
        "Marine Corps": ["Private First Class"],
        "Navy": ["Seaman Apprentice"],
        "Air Force": ["Airman"],
        "Space Force": ["Specialist 2"],
    },
    "E-3": {
        "Army": ["Private First Class"],
        "Marine Corps": ["Lance Corporal"],
        "Navy": ["Seaman"],
        "Air Force": ["Airman First Class"],
        "Space Force": ["Specialist 3"],
    },
    "E-4": {
        "Army": ["Corporal", "Specialist"],
        "Marine Corps": ["Corporal"],
        "Navy": ["Petty Officer Third Class"],
        "Air Force": ["Senior Airman"],
        "Space Force": ["Specialist 4"],
    },
    "E-5": {
        "Army": ["Sergeant"],
        "Marine Corps": ["Sergeant"],
        "Navy": ["Petty Officer Second Class"],
        "Air Force": ["Staff Sergeant"],
        "Space Force": ["Sergeant"],
    },
    "E-6": {
        "Army": ["Staff Sergeant"],
        "Marine Corps": ["Staff Sergeant"],
        "Navy": ["Petty Officer First Class"],
        "Air Force": ["Technical Sergeant"],
        "Space Force": ["Technical Sergeant"],
    },
    "E-7": {
        "Army": ["Sergeant First Class"],
        "Marine Corps": ["Gunnery Sergeant"],
        "Navy": ["Chief Petty Officer"],
        "Air Force": ["Master Sergeant", "First Sergeant"],
        "Space Force": ["Master Sergeant"],
    },
    "E-8": {
        "Army": ["Master Sergeant", "First Sergeant"],
        "Marine Corps": ["Master Sergeant", "First Sergeant"],
        "Navy": ["Senior Chief Petty Officer"],
        "Air Force": ["Senior Master Sergeant", "First Sergeant"],
        "Space Force": ["Senior Master Sergeant"],
    },
    "E-9": {
        "Army": ["Sergeant Major", "Command Sergeant Major"],
        "Marine Corps": ["Master Gunnery Sergeant", "Sergeant Major"],
        "Navy": ["Master Chief Petty Officer", "Fleet/Command Master Chief Petty Officer"],
        "Air Force": ["Chief Master Sergeant", "First Sergeant", "Command Chief Master Sergeant"],
        "Space Force": ["Chief Master Sergeant"],
    },
}
WARRANT_OFFICER_PAYGRADES = {
    "W-1": {
        "Army": ["Warrant Officer 1"],
        "Marine Corps": ["Warrant Officer 1"],
        "Navy": ["USN Warrant Officer 1"],
    },
    "W-2": {
        "Army": ["Chief Warrant Officer 2"],
        "Marine Corps": ["Chief Warrant Officer 2"],
        "Navy": ["USN Chief Warrant Officer 2"],
    },
    "W-3": {
        "Army": ["Chief Warrant Officer 3"],
        "Marine Corps": ["Chief Warrant Officer 3"],
        "Navy": ["USN Chief Warrant Officer 3"],
    },
    "W-4": {
        "Army": ["Chief Warrant Officer 4"],
        "Marine Corps": ["Chief Warrant Officer 4"],
        "Navy": ["USN Chief Warrant Officer 4"],
    },
    "W-5": {
        "Army": ["Chief Warrant Officer 5"],
        "Marine Corps": ["Chief Warrant Officer 5"],
        "Navy": ["USN Chief Warrant Officer 5"],
    },
}
OFFICER_PAYGRADES = {
    "O-1": {
        "Army": ["Second Lieutenant"],
        "Marine Corps": ["Second Lieutenant"],
        "Navy": ["Ensign"],
        "Air Force": ["Second Lieutenant"],
        "Space Force": ["Second Lieutenant"],
    },
    "O-2": {
        "Army": ["First Lieutenant"],
        "Marine Corps": ["First Lieutenant"],
        "Navy": ["Lieutenant Junior Grade"],
        "Air Force": ["First Lieutenant"],
        "Space Force": ["First Lieutenant"],
    },
    "O-3": {
        "Army": ["Captain"],
        "Marine Corps": ["Captain"],
        "Navy": ["Lieutenant"],
        "Air Force": ["Captain"],
        "Space Force": ["Captain"],
    },
    "O-4": {
        "Army": ["Major"],
        "Marine Corps": ["Major"],
        "Navy": ["Lieutenant Commander"],
        "Air Force": ["Major"],
        "Space Force": ["Major"],
    },
    "O-5": {
        "Army": ["Lieutenant Colonel"],
        "Marine Corps": ["Lieutenant Colonel"],
        "Navy": ["Commander"],
        "Air Force": ["Lieutenant Colonel"],
        "Space Force": ["Lieutenant Colonel"],
    },
    "O-6": {
        "Army": ["Colonel"],
        "Marine Corps": ["Colonel"],
        "Navy": ["Captain"],
        "Air Force": ["Colonel"],
        "Space Force": ["Colonel"],
    },
    "O-7": {
        "Army": ["Brigadier General"],
        "Marine Corps": ["Brigadier General"],
        "Navy": ["Rear Admiral Lower Half"],
        "Air Force": ["Brigadier General"],
        "Space Force": ["Brigadier General"],
    },
    "O-8": {
        "Army": ["Major General"],
        "Marine Corps": ["Major General"],
        "Navy": ["Rear Admiral Upper Half"],
        "Air Force": ["Major General"],
        "Space Force": ["Major General"],
    },
    "O-9": {
        "Army": ["Lieutenant General"],
        "Marine Corps": ["Lieutenant General"],
        "Navy": ["Vice Admiral"],
        "Air Force": ["Lieutenant General"],
        "Space Force": ["Lieutenant General"],
    },
    "O-10": {
        "Army": ["General"],
        "Marine Corps": ["General"],
        "Navy": ["Admiral"],
        "Air Force": ["General"],
        "Space Force": ["General"],
    },
}
PAYGRADES = {
    **ENLISTED_PAYGRADES,
    **WARRANT_OFFICER_PAYGRADES,
    **OFFICER_PAYGRADES,
}


# sources:
    # https://en.wikipedia.org/wiki/List_of_United_States_Army_careers
    # https://en.wikipedia.org/wiki/List_of_United_States_Marine_Corps_MOS
ENLISTED_POSITIONS = {
    "Army": {
        "00F": "MOS Immaterial NGB",
        "00G": "MOS Immaterial USAR",
        "00S": "Special Duty Assignment AFSC",
        "00Z": "Command Sergeant Major",
        "09B": "Trainee Unassigned",
        "09C": "Trainee Language",
        "09D": "College Trainee",
        "09G": "ARNG on Active Duty Medical Hold",
        "09H": "USAR on Active Duty Medical Hold",
        "09J": "GED Completion Program",
        "09M": "March 2 Success",
        "09N": "Nurse Corps Candidate",
        "09R": "Simultaneous MBR Program",
        "09S": "Commissioned Officer Candidate",
        "09T": "College Student Army National Guard Officer Program",
        "09U": "Prior Service or Branch Transfer without Defined MOS",
        "09W": "Warrant Officer Candidate",
        "11B": "Infantryman",
        "11C": "Indirect Fire Infantryman",
        "11X": "Undetermined Infantry",
        "11Z": "Infantry Senior Sergeant",
        "12A": "Engineer Senior Sergeant",
        "12B": "Combat Engineer",
        "12C": "Bridge Crewmember",
        "12D": "Diver",
        "12G": "Quarrying Specialist (RC)",
        "12H": "Construction Engineering Supervisor",
        "12K": "Plumber",
        "12M": "Firefighter",
        "12N": "Horizontal Construction Engineer",
        "12P": "Prime Power Production Specialist",
        "12Q": "Power Line Distribution Specialist (RC)",
        "12R": "Interior Electrician",
        "12T": "Technical Engineer",
        "12W": "Carpentry and Masonry Specialist",
        "12X": "General Engineering Supervisor",
        "12Y": "Geospatial Engineer",
        "12Z": "Combat Engineering Senior Sergeant",
        "13B": "Cannon Crewmember",
        "13F": "Fire Support Specialist",
        "13J": "Fire Control Specialist",
        "13M": "MLRS/HIMARS Crewmember",
        "13R": "Field Artillery Firefinder Radar Operator",
        "13T": "Field Artillery Surveyor/Meteorological Crewmember",
        "13U": "Field Artillery Recruit",
        "13Z": "Field Artillery Senior Sergeant/Sergeant Major",
        "14E": "PATRIOT Fire Control Enhanced Operator/Maintainer",
        "14G": "Air Defense Battle Management System Operator",
        "14H": "Air Defense Enhanced Early Warning System Operator",
        "14P": "Air and Missile Defense Crewmember",
        "14S": "Avenger Crew Member",
        "14T": "PATRIOT Launching Station Enhanced Operator/Maintainer",
        "14U": "Air Defense Artillery Recruit",
        "14Z": "Air Defense Artillery (ADA) Senior Sergeant",
        "15B": "Aircraft Powerplant Repairer",
        "15C": "MQ-1 (Gray Eagle) Operator",
        "15D": "Aircraft Powertrain Repairer",
        "15E": "RQ-7 (Shadow) Repairer",
        "15F": "Aircraft Electrician",
        "15G": "Aircraft Structural Repairer",
        "15H": "Aircraft Pneudraulics Repairer",
        "15K": "Aircraft Components Repair Supervisor",
        "15M": "MQ-1 (Gray Eagle) Repairer",
        "15N": "Avionic Mechanic",
        "15P": "Aviation Operations Specialist",
        "15Q": "Air Traffic Control Operator",
        "15R": "AH-64 Attack Helicopter Repairer",
        "15T": "UH-60 Helicopter Repairer",
        "15U": "CH-47 Helicopter Repairer",
        "15V": "Observation/Scout Helicopter Repairer (RC)",
        "15W": "RQ-7 (Shadow) Operator",
        "15X": "AH-64A Armament/Electrical/Avionics Systems Repairer",
        "15Y": "AH-64D Armament/Electrical/Avionic Systems Repairer",
        "15Z": "Aircraft Maintenance Senior Sergeant",
        "17C": "Cyber Operations Specialist",
        "17E": "Electronic Warfare Specialist",
        "17Z": "Cyberspace and Electromagnetic Activities (CEMA) Senior Sergeant",
        "18B": "Special Forces Weapons Sergeant - SGT-SFC",
        "18C": "Special Forces Engineer Sergeant - SGT-SFC",
        "18D": "Special Forces Medical Sergeant - SGT-SFC",
        "18E": "Special Forces Communications Sergeant - SGT-SFC",
        "18F": "Special Forces Intelligence Sergeant - SSG-SFC",
        "18X": "Special Forces Candidate",
        "18Z": "Special Forces Senior Sergeant - MSG-CSM",
        "25B": "Information Technology Specialist",
        "25D": "Cyber Network Defender",
        "25E": "Electromagnetic Spectrum Manager",
        "25H": "Network Communication Systems Specialist",
        "25S": "Satellite Communications Systems Operator/Maintainer",
        "25U": "Signal Support Systems Specialist",
        "25W": "Telecommunications Operations Chief",
        "25X": "Chief Signal NCO",
        "25Z": "Visual Information Operations Chief",
        "27D": "Paralegal Specialist",
        "31B": "Military Police",
        "31D": "CID Special Agent",
        "31E": "Internment/Resettlement Specialist",
        "31K": "Working Dog Handler",
        "31Z": "Military Police Senior Sergeant",
        "09L": "Interpreter/Translator",
        "35F": "Intelligence Analyst",
        "35G": "Geospatial Intelligence Imagery Analyst",
        "35L": "Counterintelligence Special Agent",
        "35M": "Human Intelligence Collector",
        "35N": "Signals Intelligence Analyst",
        "35P": "Cryptologic Linguist",
        "35S": "Signals Collector/Analyst",
        "35T": "Military Intelligence Systems Maintainer/Integrator",
        "35V": "Signals Intelligence Senior Sergeant/Chief Signals Intelligence Sergeant",
        "35X": "Intelligence Senior Sergeant/Chief Intelligence Sergeant",
        "35Y": "Chief Counterintelligence/Human Intelligence Sergeant",
        "35Z": "Signals Intelligence (Electronic Warfare) / Senior Sergeant/ Chief",
        "36B": "Financial Management Technician",
        "37F": "Psychological Operations Specialist",
        "38B": "Civil Affairs Specialist",
        "38R": "Civil Reconnaissance Sergeant",
        "38W": "Civil Affairs Medic",
        "38Z": "Civil Affairs Senior Sergeant",
        "42A": "Human Resources Specialist",
        "42R": "Musician",
        "42S": "Special Band Member",
        "46T": "Visual Information Equipment Operator-Maintainer",
        "46S": "Public Affairs Mass Communications Specialist",
        "46V": "Visual Information Specialist",
        "46Z": "Chief Public Affairs NCO",
        "68A": "Biomedical Equipment Specialist",
        "68B": "Orthopedic Specialist",
        "68C": "Practical Nursing Specialist-(LPN/LVN)",
        "68D": "Operating Room Specialist",
        "68E": "Dental Specialist",
        "68F": "Physical Therapy Specialist",
        "68G": "Patient Administration Specialist ",
        "68H": "Optical Laboratory Specialist",
        "68J": "Medical Logistics Specialist",
        "68K": "Medical Laboratory Specialist",
        "68L": "Occupational Therapy Specialist",
        "68M": "Nutrition Care Specialist",
        "68N": "Cardiovascular Specialist ( Discontinued)",
        "68P": "Radiology Specialist",
        "68Q": "Pharmacy Specialist",
        "68R": "Veterinary Food Inspection Specialist",
        "68S": "Preventive Medicine Specialist",
        "68T": "Animal Care Specialist",
        "68U": "Ear, Nose, and Throat (ENT) Specialist (Discontinued)",
        "68V": "Respiratory Specialist",
        "68W": "Combat Medic Specialist",
        "68X": "Behavioral Health Specialist",
        "68Y": "Eye Specialist",
        "68Z": "Chief Medical NCO",
        "74D": "Chemical, Biological, Radiological and Nuclear (CBRN) Specialist",
        "88H": "Cargo Specialist",
        "88K": "Watercraft Operator",
        "88L": "Watercraft Engineer",
        "88M": "Motor Transport Operator",
        "88N": "Transportation Management Coordinator",
        "88P": "Railway Equipment Repairer (RC)",
        "88T": "Railway Section Repairer (RC)",
        "88U": "Railway Operations Crew Member (RC)",
        "88Z": "Transportation Senior Sergeant",
        "89A": "Ammunition Stock Control and Accounting Specialist",
        "89B": "Ammunition Specialist",
        "89D": "Explosive Ordnance Disposal Specialist",
        "91A": "M1 Abrams Tank System Maintainer ",
        "91B": "Wheeled Vehicle Mechanic ",
        "91C": "Utilities Equipment Repairer ",
        "91D": "Power Generation Equipment Repairer ",
        "91E": "Allied Trades Specialist ",
        "91F": "Small Arms/Towed Artillery Repairer ",
        "91G": "Fire Control Repairer ",
        "91H": "Track Vehicle Repairer ",
        "91J": "Quartermaster and Chemical Equipment Repairer ",
        "91L": "Construction Equipment Repairer ",
        "91M": "Bradley Fighting Vehicle System Maintainer ",
        "91P": "Self Propelled Artillery Systems Maintainer ",
        "91S": "Stryker Systems Maintainer",
        "91X": "Maintenance Supervisor ",
        "91Z": "Senior Maintenance Supervisor ",
        "94A": "Land Combat Electronic Missile System Repairer ",
        "94D": "Air Traffic Control Equipment Repairer",
        "94E": "Radio & Communications Security (COMSEC) Equipment Repairer",
        "94F": "Computer/Detection Systems Repairer",
        "94H": "Test Measurement and Diagnostic Equipment (TMDE) Maintenance Support Specialist",
        "94M": "Radar Repairer",
        "94P": "Multiple Launch Rocket System (MLRS) Repairer ",
        "94R": "Avionic and Survivability Repairer",
        "94S": "PATRIOT System Repairer",
        "94T": "AVENGER System Repairer",
        "94W": "Electronic Maintenance Chief",
        "94X": "Senior Missile Systems Maintainer",
        "94Y": "Integrated Family of Test Equipment (IFTE) Operator/Maintainer",
        "94Z": "Senior Electronic Maintenance Chief",
        "92A": "Automated Logistical Specialist",
        "92F": "Petroleum Supply Specialist",
        "92G": "Culinary Specialist",
        "92L": "Petroleum Laboratory Specialist",
        "92M": "Mortuary Affairs Specialist",
        "92R": "Parachute Rigger",
        "92S": "Shower/Laundry and Clothing Repair Specialist",
        "92W": "Water Treatment Specialist",
        "92Y": "Unit Supply Specialist",
        "92Z": "Senior Noncommissioned Logistician",
    },
    "Marine Corps": {
        "0100": "Basic Administrative Marine",
        "0111": "Administrative Specialist",
        "0147": "Equal Opportunity Advisor",
        "0149": "Substance Abuse Control Specialist",
        "0161": "Postal Clerk",
        "0171": "Manpower Information Systems",
        "0200": "Basic Intelligence Marine",
        "0211": "Counterintelligence/Human Source Intelligence (CI/HUMINT)",
        "0212": "Technical Surveillance Countermeasures (TSCM) Specialist",
        "0231": "Intelligence Specialist",
        "0239": "Intelligence Analyst",
        "0241": "Imagery Analysis Specialist",
        "0245": "Target Mensuration Analyst",
        "0261": "Geographic Intelligence Specialist",
        "0271": "Aviation Intelligence Specialist",
        "0275": "Collection Manager",
        "0282": "Tactical Debriefer",
        "0283": "Advanced Foreign Counterintelligence Specialist",
        "0287": "Military Source Operations Specialist",
        "0289": "Strategic Debriefing Specialist",
        "0291": "Intelligence Chief",
        "0293": "Advanced Military Source Operations Specialist",
        "0300": "Basic Infantry Marine – Sgt–Pvt",
        "0311": "Rifleman",
        "0313": "Light Armored Reconnaissance Marine",
        "0316": "Combat Rubber Reconnaissance Craft (CRRC) Coxswain",
        "0317": "Scout Sniper",
        "0321": "Reconnaissance Marine",
        "0323": "Reconnaissance Marine, Parachute Qualified",
        "0324": "Reconnaissance Marine, Combatant Diver Qualified",
        "0326": "Reconnaissance Marine, Parachute and Combatant Diver Qualified",
        "0331": "Machine Gunner",
        "0341": "Mortarman",
        "0352": "Antitank Missile Gunner",
        "0363": "Light Armored Reconnaissance Unit Leader",
        "0365": "Infantry Squad Leader",
        "0367": "Light Armored Reconnaissance Master Gunner",
        "0369": "Infantry Unit Leader",
        "0372": "Critical Skills Operator (CSO)",
        "0393": "Light Armored Reconnaissance Operations Chief",
        "0399": "Operations Chief",
        "0400": "Basic Logistics Marine",
        "0411": "Maintenance Management Specialist",
        "0441": "Logistics Specialist",
        "0451": "Airborne and Air Delivery Specialist",
        "0471": "Personnel Retrieval and Processing Specialist",
        "0472": "Personnel Retrieval and Processing Technician",
        "0477": "Expeditionary Logistics Instructor (ELI)",
        "0491": "Logistics/Mobility Chief",
        "0500": "Basic MAGTF Marine",
        "0511": "MAGTF Planning Specialist",
        "0521": "Psychological Operations (PSYOP) Specialist",
        "0522": "Psychological Operations (PSYOP) Non-Commissioned Officer",
        "0531": "Civil Affairs Noncommissioned Officer",
        "0532": "Civil Affairs Specialist",
        "0538": "Female Engagement Specialist",
        "0539": "Civil-Military Operations (CMO) Chief",
        "0551": "Information Operations Specialist",
        "0570": "Advisor",
        "0571": "Operational Advisor",
        "0612": "Tactical Switching Operator",
        "0621": "Transmission Systems Operator",
        "0627": "Satellite Communications Operator",
        "0631": "Network Administrator",
        "0671": "Data Systems Administrator",
        "0681": "Information Security Technician",
        "0689": "Cybersecurity Chief",
        "0699": "Communications Chief",
        "0811": "Field Artillery Cannoneer",
        "0814": "High Mobility Artillery Rocket System Operator",
        "0842": "Field Artillery Radar Operator",
        "0844": "Field Artillery Fire Direction Control Marine",
        "0847": "Field Artillery Sensor Support Marine",
        "0848": "Field Artillery Fire Direction Control Operations Chief",
        "0861": "Fire Support Marine",
        "0871": "Field Artillery Scout Observer",
        "0911": "Drill Instructor",
        "0913": "Marine Combat Instructor",
        "0914": "Marine Special Operations Forces Instructor",
        "0916": "Martial Arts Instructor",
        "0918": "Water Safety/Survival Instructor",
        "0919": "Force Fitness Instructor",
        "0931": "Marksmanship Instructor",
        "0932": "Small Arms Weapons Instructor",
        "0933": "Marksmanship Coach",
        "0951": "Formal School Instructor",
        "1141": "Electrician",
        "1142": "Electrical Equipment Repair Specialist",
        "1161": "Refrigeration and Air Conditioning Technician",
        "1169": "Utilities Chief",
        "1171": "Water Support Technician",
        "1316": "Metal Worker",
        "1341": "Engineer Equipment Mechanic",
        "1342": "Small Craft Mechanic",
        "1343": "Assault Breacher Vehicle Mechanic",
        "1345": "Engineer Equipment Operator",
        "1349": "Engineer Equipment Chief",
        "1361": "Engineer Assistant",
        "1371": "Combat Engineer",
        "1391": "Bulk Fuel Specialist",
        "1392": "Petroleum Quality Assurance and Additization Specialist",
        "1711": "Offensive Cyberspace Warfare Operator",
        "1721": "Defensive Cyberspace Warfare Operator",
        "1751": "Influence Specialist",
        "1795": "Influence Chief",
        "1799": "Cyberspace Warfare Chief",
        "1833": "Assault Amphibious Vehicle Marine",
        "1834": "ACV Marine",
        "1868": "Assault Amphibious Master Gunner",
        "1869": "Senior Armor NCO",
        "2111": "Small Arms Repairer/Technician",
        "2112": "Precision Weapons Repairer",
        "2131": "Artillery Systems Technician",
        "2141": "Assault Amphibious Vehicle Repairer/Technician",
        "2146": "Heavy Ordnance Vehicle Repairer/Technician",
        "2147": "Light Armored Vehicle Repairer/Technician",
        "2161": "Machinist",
        "2171": "Electro-Optical Ordnance Repairer/Technician",
        "2181": "Senior Ground Ordnance Weapons Chief",
        "2311": "Ammunition Technician",
        "2336": "Explosive Ordnance Disposal Technician",
        "2611": "Cryptologic Cyberspace Analyst",
        "2621": "Communications/Electronic Warfare Operator",
        "2623": "Radio Reconnaissance Marine",
        "2631": "Electronic Intelligence Intercept Operator/Analyst",
        "2641": "Cryptologic Linguist Operator Analyst",
        "2651": "ISR Systems Engineer",
        "2671": "Middle East Cryptologic Linguist",
        "2673": "Asia-Pacific Cryptologic Linguist",
        "2674": "European Cryptologic Linguist",
        "2676": "Central Asian Cryptologic Linguist",
        "2691": "Signals Intelligence/Electronic Warfare Chief",
        "2841": "Ground Electronics Transmission Systems Maintainer",
        "2847": "Ground Electronics Telecommunications and Information Systems Maintainer",
        "2862": "Ground Electronics Systems Maintenance Technician",
        "2871": "Calibrations Technician",
        "2874": "Metrology Technician",
        "2887": "Artillery Electronics Technician",
        "2891": "Ground Electronics Systems Maintenance Chief",
        "3043": "Supply Administration and Operations Specialist",
        "3044": "Contract Specialist",
        "3051": "Warehouse Clerk",
        "3052": "Preservation, Packaging, Packing, and Marking Specialist",
        "3072": "Aviation Supply Clerk",
        "3112": "Distribution Management Specialist",
        "3152": "Preservation, Packaging, Packing, and Marketing Specialist",
        "3381": "Food Service Specialist",
        "3372": "Marine Aide",
        "3432": "Finance Technician",
        "3441": "Non-appropriated Fund Audit Technician",
        "3451": "Fiscal/Budget Technician",
        "3521": "Automotive Organizational Technician",
        "3523": "Vehicle Recovery Mechanic",
        "3524": "Fuel and Electrical Systems Mechanic",
        "3529": "Motor Transport Maintenance Chief",
        "3531": "Motor Vehicle Operator",
        "3533": "Logistics Vehicle Systems Operator",
        "3537": "Motor Transport Operations Chief",
        "4133": "Morale, Welfare, Recreation Specialist",
        "4313": "Broadcast Journalist",
        "4341": "Combat Correspondent",
        "4421": "Legal Services Specialist",
        "4422": "Legal Services Court Reporter",
        "4511": "Recruiting Station Marketing & Communication Marine",
        "4512": "Combat Graphics Specialist",
        "4531": "Combat Mass Communicator",
        "4541": "Combat Photographer",
        "4571": "Combat Videographer",
        "4591": "Communication and Strategy Operations Chief",
        "4612": "Production Specialist",
        "4641": "Combat Photographer",
        "4671": "Combat Videographer",
        "4691": "Combat Camera Chief",
        "4821": "Career Retention Specialist",
        "5511": "Member, The President's Own, United States Marine Band",
        "5512": "Member, The Commandant's Own, United States Marine Drum and Bugle Corps",
        "5524": "Musician",
        "5711": "Chemical, Biological, Radiological, and Nuclear Defense Specialist",
        "5769": "Chemical, Biological, Radiological, and Nuclear Defense Chief",
        "5811": "Military Police",
        "5812": "Working Dog Handler",
        "5821": "Criminal Investigator CID Agent",
        "5831": "Correctional Specialist",
        "5939": "Aviation Communication Systems Technician",
        "5941": "Aviation Primary Surveillance Radar Repair Man",
        "5948": "Aviation Radar Technician",
        "5952": "Air Traffic Control Navigational Aids Technician",
        "5953": "Air Traffic Control Radar Technician",
        "5954": "Air Traffic Control Communications Technician",
        "5959": "Air Traffic Control Systems Maintenance Chief",
        "5974": "Tactical Data Systems Technician",
        "5979": "Tactical Air Operations/Air Defense Systems Technician",
        "5993": "Electronics Maintenance Chief",
        "6011": "Aviation Production Controller",
        "6012": "Aviation Maintenance Controller",
        "6013": "Aircraft Mechanic",
        "6018": "Quality Assurance Representative",
        "6019": "Aircraft Maintenance Chief",
        "6042": "Aviation Support Equipment Asset Manager",
        "6046": "Aircraft Maintenance Data Specialist",
        "6048": "Flight Equipment Technician",
        "6062": "Aircraft Intermediate Level Hydraulic/Pneumatic Mechanic",
        "6073": "Aircraft Maintenance Support Equipment Electrician/Refrigeration Mechanic",
        "6074": "Cryogenics Equipment Operator",
        "6092": "Aircraft Intermediate Level Structures Mechanic",
        "6113": "Helicopter Mechanic, CH-53",
        "6114": "Helicopter Mechanic, UH/AH-1",
        "6116": "Tiltrotor Mechanic, MV-22",
        "6173": "Helicopter Crew Chief, CH-53",
        "6174": "Helicopter Crew Chief, UH-1N/Y",
        "6176": "Tiltrotor Crew Chief, MV-22",
        "6217": "Fixed-Wing Aircraft Mechanic, F/A-18",
        "6218": "Fixed-Wing Aircraft Mechanic, F35",
        "6531": "Aircraft Ordnance Technician",
        "6541": "Aviation Ordnance Systems Technician",
        "6591": "Aviation Ordnance Chief",
        "6672": "Aviation Supply Specialist",
        "6694": "Aviation Logistics Information Management System Specialist",
        "6842": "METOC Analyst Forecaster",
        "6852": "METOC Impact Analyst",
        "7011": "Expeditionary Airfield Systems Technician",
        "7041": "Aviation Operations Specialist",
        "7051": "Aircraft Rescue and Firefighting Specialist",
        "7212": "Low Altitude Air Defense Gunner",
        "7236": "Tactical Air Defense Controller",
        "7242": "Air Support Operations Operator",
        "7257": "Air Traffic Controller",
        "7291": "Senior Air Traffic Controller",
        "7313": "Helicopter Specialist, AH-1Z/UH-1Y",
        "7314": "Unmanned Aerial Vehicle Air Vehicle Operator",
        "7316": "Small Unmanned Aerial System Operator",
        "7321": "Unmanned Aircraft System Operator, MQ-21",
        "7372": "Tactical Systems Operator/Mission Specialist",
        "7382": "Airborne Radio Operator/In-flight Refueling Observer/Loadmaster",
        "8011": "Basic Marine with Enlistment Guarantee",
        "8013": "Special Assignment—Enlisted",
        "8021": "Career Planner",
        "8023": "Parachutist",
        "8024": "Combatant Diver Marine",
        "8028": "MECEP Participant",
        "8056": "Hazardous Material/Hazardous Waste Staff NCO",
        "8071": "Special Operations Capabilities Specialist",
        "8156": "Marine Security Guard",
        "8411": "Recruiter",
        "8412": "Career Recruiter",
        "8511": "Drill Instructor",
        "8531": "Marksmanship Instructor",
        "8541": "Scout Sniper",
        "8621": "Surveillance Sensor Operator",
        "8991": "Sergeant Major of the Marine Corps",
        "8999": "Sergeant Major/First Sergeant",
        "9051": "Graves Registration Specialist",
        "9900": "General Service Marine",
        "9051": "Graves Registration Specialist",
        "9811": "Member, The President's Own, United States Marine Band",
        "9812": "Member, The Commandant's Own, U.S. Marine Drum & Bugle Corps",
        "9900": "General Service Marine",
        "9915": "Special Assignment—Enlisted",
        "9916": "Billet Designator—Enlisted",
        "9917": "College Degree—Enlisted",
        "9928": "MECEP Participant",
        "9935": "Special Technical Operations",
        "9936": "Substance Abuse Control Specialist",
        "9952": "Combatant Diver Marine",
        "9954": "Hazardous Material/Hazardous Waste Staff NCO",
        "9962": "Parachutist",
        "9971": "Basic Marine with Enlistment Guarantee",
        "9972": "Aircrew Trainee",
        "9991": "Sergeant Major of the Marine Corps",
        "9999": "Sergeant Major-First Sergeant",
    },
    "Navy": {
        "AB": "Aviation Boatswain's Mate",
        "AC": "Air Traffic Controller",
        "AD": "Aviation Machinist's Mate",
        "AE": "Aviation Electrician's Mate",
        "AG": "Aerographer's Mate",
        "AM": "Aviation Structural Mechanic",
        "AO": "Aviation Ordnanceman",
        "AS": "Aviation Support Equipment Technician",
        "AT": "Aviation Electronics Technician",
        "AW": "Naval Aircrewman",
        "AZ": "Aviation Maintenance Administrationman",
        "BM": "Boatswain's Mate",
        "BU": "Builder",
        "CE": "Construction Electrician",
        "CM": "Construction Mechanic",
        "CS": "Culinary Specialist",
        "CT": "Cryptologic Technician",
        "CWT": "Cyber Warfare Technician",
        "DC": "Damage Controlman",
        "EA": "Engineering Aide",
        "EM": "Electrician's Mate",
        "EN": "Engineman",
        "EO": "Equipment Operator",
        "EOD": "Explosive Ordnance Disposal",
        "ET": "Electronics Technician",
        "FC": "Fire Controlman",
        "FT": "Fire Control Technician",
        "GM": "Gunner's Mate",
        "GS": "Gas Turbine System Technician",
        "HM": "Hospital Corpsman",
        "HT": "Hull Maintenance Technician",
        "IC": "Interior Communications Electrician",
        "IS": "Intelligence Specialist",
        "IT": "Information Systems Technician",
        "LN": "Legalman",
        "LS": "Logistics Specialist",
        "MA": "Master-at-Arms",
        "MC": "Mass Communication Specialist",
        "MM": "Machinist's Mate",
        "MN": "Mineman",
        "MR": "Machinery Repairman",
        "MT": "Missile Technician",
        "MU": "Musician",
        "NC": "Navy Counselor",
        "ND": "Navy Diver",
        "OS": "Operations Specialist",
        "PR": "Aircrew Survival Equipmentman",
        "PS": "Personnel Specialist",
        "QM": "Quartermaster",
        "RP": "Religious Program Specialist",
        "RS": "Retail Services Specialist",
        "RW": "Robotics Warfare Specialist",
        "SB": "Special Warfare Boat Operator",
        "SO": "Special Warfare Operator",
        "ST": "Sonar Technician",
        "SW": "Steelworker",
        "TM": "Torpedoman's Mate",
        "UT": "Utilitiesman",
        "YN": "Yeoman"
    }
}
WARRANT_OFFICER_POSITIONS = {
    "Army": {
        "001A": "Unqual in Auth WO MOS",
        "002A": "Patient",
        "003A": "Student",
        "004A": "Duties Unassigned",
        "011A": "Branch/MOS Immaterial",
        "019G": "Army National Guard on Active Duty Medical Hold",
        "019H": "US Army Reserve on Active Duty Medical Hold",
        "120A": "Construction Engineer Technician",
        "125D": "Geospatial Information Technician",
        "131A": "Field Artillery Technician",
        "140A": "Command and Control Systems Integrator",
        "140K": "Air And Missile Defense Tactician",
        "140L": "Air and Missile Defense Technician",
        "140Z": "Air Defense Artillery Immaterial",
        "150A": "Air Traffic and Air Space Management Technician",
        "150U": "Unmanned Aircraft Systems Operations Technician",
        "151A": "Aviation Maintenance Technician",
        "152B": "OH-58A/C Scout Pilot",
        "152C": "OH-6 Pilot",
        "152D": "OH-58D Pilot",
        "152E": "AH-64E Attack Pilot",
        "152F": "AH-64A Attack Pilot",
        "152G": "AH-1 Attack Pilot",
        "152H": "AH-64D Attack Pilot",
        "153A": "Rotary Wing Aviator",
        "153B": "UH-1 Pilot",
        "153D": "UH-60 Pilot",
        "153DD": "UH-60 MEDEVAC Pilot",
        "153E": "MH-60 Pilot",
        "153L": "UH-72A Pilot",
        "153M": "UH-60M Pilot",
        "154C": "CH-47D Pilot",
        "154E": "MH-47 Pilot",
        "154F": "CH-47F Pilot",
        "155A": "Fixed Wing Aviator",
        "155E": "C-12 Pilot",
        "155F": "Jet Aircraft Pilot",
        "155G": "O-5A/EO-5B/RC-7 Pilot",
        "170A": "Cyber Operations Technician",
        "170B": "Cyber Electromagnetic Activities Technician",
        "170D": "Cyber Capabilities Developer Technician",
        "180A": "Special Forces Warrant Officer",
        "255A": "Information Services Technician",
        "255N": "Network Management Technician",
        "255S": "Information Protection Technician",
        "255Z": "Senior Network Operations Technician",
        "270A": "Legal Administrator",
        "311A": "CID Special Agent",
        "350F": "All Source Intelligence Technician",
        "350G": "Imagery Intelligence Technician",
        "351L": "Counterintelligence Supervisory Special Agent",
        "351M": "Human Intelligence Collection Technician",
        "351Y": "Area Intelligence Technician",
        "351Z": "Defense Attaché System Technician",
        "352N": "Signal Intelligence Analysis Technician",
        "352P": "Voice Intercept Technician",
        "352S": "Signals Collector Technician",
        "353T": "Intelligence Systems Maintenance Technician",
        "420A": "Human Resources Technician",
        "420C": "Bandmaster",
        "420T": "Talent Acquisitions Technician",
        "640A": "Food Safety Officer",
        "670A": "Health Services Maintenance Technician",
        "740A": "Chemical, Biological, Radiological and Nuclear Warrant Officer",
        "880A": "Marine Deck Officer",
        "881A": "Marine Engineering Officer",
        "882A": "Mobility Officer",
        "890A": "Ammunition Warrant Officer",
        "913A": "Armament Systems Maintenance Warrant Officer",
        "914A": "Allied Trades Warrant Officer",
        "915A": "Automotive Maintenance Warrant Officer",
        "915E": "Senior Automotive Maintenance Warrant Officer",
        "919A": "Engineer Equipment Maintenance Warrant Officer",
        "920A": "Property Accounting Technician",
        "920B": "Supply Systems Technician",
        "921A": "Airdrop Systems Technician",
        "922A": "Food Service Technician",
        "923A": "Petroleum Systems Technician",
    }
}
OFFICER_POSITIONS = {
    "Army": {
        "00A": "Duties Unassigned",
        "00B": "General Officer",
        "00C": "Relieved from Duty",
        "00D": "Newly Commissioned Officer",
        "00E": "Student Officer",
        "01A": "Officer Generalist",
        "01B": "Aviation/Infantry/Armor/MI Immaterial",
        "01C": "Chemical/Engineer/MP Immaterial",
        "01D": "Financial Management/Adjutant General Immaterial",
        "02A": "Combat Arms Generalist",
        "02B": "Infantry/Armor Immaterial",
        "02C": "Infantry/Armor/Field Artillery/Engineer Immaterial",
        "03A": "Infantry/Armor Immaterial",
        "05A": "Army Medical Department",
        "09G": "Army National Guard on Active Duty Medical Hold",
        "09H": "US Army Reserve on Active Duty Medical Hold",
        "11A": "Infantry Officer",
        "12A": "Engineer General",
        "13A": "Field Artillery Officer",
        "14A": "Air Defense Artillery Officer",
        "15A": "Aviation Officer",
        "15B": "Aviation Combined Arms Operations",
        "15C": "Aviation All-Source Intelligence Officer",
        "15D": "Aviation Maintenance Officer",
        "17A": "Cyber Warfare Officer",
        "17B": "Cyber Electromagnetic Activities Officer",
        "17D": "Cyber Capabilities Development Officer",
        "17X": "Cyber Officer Designated",
        "18A": "Special Forces Officer",
        "19A": "Armor Officer",
        "25A": "Signal General",
        "26A": "Network Systems Engineer",
        "26B": "Information Systems Engineer",
        "26Z": "Senior Information Network Engineer",
        "27A": "Judge Advocate",
        "27B": "Military Judge",
        "30A": "Information Operations Officer",
        "31A": "Military Police",
        "34A": "Strategic Intelligence Officer",
        "35A": "Military Intelligence Officer",
        "35D": "All Source Intelligence Officer",
        "35E": "Counterintelligence Officer",
        "35F": "Human Intelligence Officer",
        "35G": "Signals Intelligence Officer",
        "36A": "Financial Manager",
        "37A": "Psychological Operations",
        "38A": "Civil Affairs Officer",
        "38G": "Military Government Specialist",
        "38S": "Special Operations Civil Affairs Officer",
        "40A": "Space Operations",
        "40C": "Army Astronaut",
        "42B": "Human Resources Officer",
        "42C": "Army Bands",
        "42H": "Senior Human Resources Officer",
        "46A": "Public Affairs General",
        "46X": "Public Affairs General",
        "47A": "USMA Professor",
        "47C": "USMA Professor of English",
        "47D": "USMA Professor of Electrical Engineering and Computer Science",
        "47E": "USMA Professor of Law",
        "47F": "USMA Professor of Systems Engineering",
        "47G": "USMA Professor of Foreign Languages",
        "47H": "USMA Professor of Physics",
        "47J": "USMA Professor of Social Sciences",
        "47K": "USMA Professor of History",
        "47L": "USMA Professor of Behavioral Sciences and Leadership",
        "47M": "USMA Professor of Chemistry",
        "47N": "USMA Professor of Mathematical Sciences",
        "47P": "USMA Professor of Geography and Environmental Engineering",
        "47Q": "USMA Professor and Associate Dean",
        "47R": "USMA Professor of Civil and Mechanical Engineering",
        "47S": "USMA Professor of Physical Education",
        "47T": "USMA Professor of Leader Development",
        "47U": "USMA Professor of Military Art and Science",
        "47V": "USMA Professor of Army Cyber",
        "48B": "Foreign Area Officer - Latin America",
        "48D": "Foreign Area Officer - South Asia",
        "48E": "Foreign Area Officer - Eurasia",
        "48F": "Foreign Area Officer - China",
        "48G": "Foreign Area Officer - Mideast/North Africa",
        "48H": "Foreign Area Officer - Northeast Asia",
        "48I": "Foreign Area Officer - Southeast Asia",
        "48J": "Foreign Area Officer - Africa",
        "48X": "Foreign Area Officer",
        "49A": "Operations Research/Systems Analysis",
        "49W": "Trained ORSA",
        "49X": "Untrained ORSA",
        "50A": "Force Development",
        "51A": "Program Management",
        "51C": "Contract Management",
        "51R": "Systems Automation Acquisition and Engineering",
        "51S": "Research and Engineering",
        "51T": "Test and Evaluation",
        "51Z": "Acquisitions",
        "52B": "Nuclear and Counter WMD Officer",
        "56A": "Command and Unit Chaplain",
        "56D": "Clinical Pastoral Educator",
        "56X": "Chaplain Candidate",
        "57A": "Simulation Operations Officer",
        "58A": "Army Marketing Officer",
        "59A": "Strategist",
        "60A": "Operational Medicine",
        "60B": "Nuclear Medicine Officer",
        "60C": "Preventive Medicine Officer",
        "60D": "Occupational Medicine Officer",
        "60F": "Pulmonary Disease/Critical Care Officer",
        "60G": "Gastroenterologist",
        "60H": "Cardiologist",
        "60J": "Obstetrician and Gynecologist",
        "60K": "Urologist",
        "60L": "Dermatologist",
        "60M": "Allergist, Clinical Immunologist",
        "60N": "Anesthesiologist",
        "60P": "Pediatrician",
        "60Q": "Pediatric Sub-Specialist",
        "60R": "Child Neurologist",
        "60S": "Ophthalmologist",
        "60T": "Otolaryngologist",
        "60U": "Child Psychiatrist",
        "60V": "Neurologist",
        "60W": "Psychiatrist",
        "61A": "Nephrologist",
        "61B": "Medical Oncologist/Hematologist",
        "61C": "Endocrinologist",
        "61D": "Rheumatologist",
        "61E": "Clinical Pharmacologist",
        "61F": "Internist",
        "61G": "Infectious Disease Officer",
        "61H": "Family Medicine",
        "61J": "General Surgeon",
        "61K": "Thoracic Surgeon",
        "61L": "Plastic Surgeon",
        "61M": "Orthopedic Surgeon",
        "61N": "Flight Surgeon",
        "61P": "Physiatrist",
        "61Q": "Radiation Oncologist",
        "61R": "Diagnostic Radiologist",
        "61U": "Pathologist",
        "61W": "Peripheral Vascular Surgeon",
        "61Z": "Neurosurgeon",
        "62A": "Emergency Physician",
        "62B": "Field Surgeon",
        "63A": "General Dentist",
        "63B": "Comprehensive Dentist",
        "63D": "Periodontist",
        "63E": "Endodontist",
        "63F": "Prosthodontist",
        "63H": "Public Health Dentist",
        "63K": "Pediatric Dentist",
        "63M": "Orthodontist",
        "63N": "Oral and Maxillofacial Surgeon",
        "63P": "Oral Pathologist",
        "63R": "Executive Dentist",
        "64A": "Field Veterinary Service",
        "64B": "Veterinary Preventive Medicine",
        "64C": "Veterinary Laboratory Animal Medicine",
        "64D": "Veterinary Pathology",
        "64E": "Veterinary Comparative Medicine",
        "64F": "Veterinary Clinical Medicine",
        "64Z": "Senior Veterinarian",
        "65A": "Occupational Therapy",
        "65B": "Physical Therapy",
        "65C": "Dietitian",
        "65D": "Physician Assistant",
        "65X": "Specialist Allied Operations",
        "66B": "Public Health Nurse",
        "66C": "Psychiatric/Mental Health Nurse",
        "66E": "Perioperative Nurse",
        "66F": "Nurse Anesthetist",
        "66G": "Obstetrics and Gynecology Nurse",
        "66H": "Medical-Surgical Nurse",
        "66N": "Generalist Nurse",
        "66P": "Family Nurse Practitioner",
        "66R": "Psychiatric Nurse Practitioner",
        "66S": "Critical Care Nurse",
        "66T": "Emergency Room Nurse",
        "66W": "Certified Nurse Midwife",
        "67A": "Health Services",
        "67C": "Preventive Medicine Sciences",
        "67D": "Behavioral Sciences",
        "67E": "Pharmacy",
        "67F": "Optometry",
        "67G": "Podiatry",
        "67J": "Aeromedical Evacuation",
        "70A": "Health Care Administration",
        "70B": "Health Services Administration",
        "70C": "Health Services Comptroller",
        "70D": "Health Services Systems Management",
        "70E": "Patient Administration",
        "70F": "Health Services Human Resources",
        "70H": "Health Services Plans and Operations",
        "70K": "Health Services Materiel",
        "71A": "Microbiology",
        "71B": "Biochemistry",
        "71E": "Clinical Laboratory",
        "71F": "Research Psychology",
        "72A": "Nuclear Medical Science",
        "72B": "Entomology",
        "72C": "Audiology",
        "72D": "Environmental Science and Engineering",
        "73A": "Social Work",
        "73B": "Clinical Psychology",
        "74A": "Chemical General",
        "88A": "Transportation General",
        "88B": "Traffic Management",
        "88C": "Marine and Terminal Operations",
        "88D": "Motor/Rail Transportation",
        "89E": "Explosive Ordnance Disposal Officer",
        "90A": "Multifunctional Logistician",
        "91A": "Materiel Maintenance and Munitions Management Officer",
        "92A": "Quartermaster Officer",
        "92D": "Aerial Delivery and Materiel",
    },
    "Marine Corps": {
        "0101": "Basic Manpower Officer",
        "0102": "Manpower Officer",
        "0149": "Substance Abuse Control Officer",
        "0160": "Postal Officer",
        "0170": "Personnel Officer",
        "0180": "Adjutant",
        "0202": "Intelligence Officer",
        "0203": "Ground Intelligence Officer",
        "0204": "Counterintelligence/Human Source Intelligence Officer",
        "0205": "Intelligence Operations and Fusion Warrant Officer",
        "0101": "Basic Manpower Officer",
        "0102": "Manpower Officer",
        "0149": "Substance Abuse Control Officer",
        "0160": "Postal Officer",
        "0170": "Personnel Officer",
        "0202": "Intelligence Officer",
        "0203": "Ground Intelligence Officer",
        "0204": "Counterintelligence/Human Source Intelligence Officer",
        "0205": "Intelligence Operations and Fusion Warrant Officer",
        "0206": "Signals Intelligence/Ground Electronic Warfare Officer",
        "0207": "Air Intelligence Officer",
        "0210": "Counterintelligence/Human Source Intelligence Operations Officer",
        "0301": "Basic Infantry Officer",
        "0302": "Infantry Officer",
        "0306": "Infantry Weapons Officer",
        "0370": "Special Operations Officer",
        "0402": "Logistics Officer",
        "0405": "Aerial Delivery Officer",
        "0407": "Personnel Retrieval and Processing Officer",
        "0408": "Fatality Management Officer",
        "0430": "Mobility Officer",
        "0502": "Force Deployment Planning and Execution Officer",
        "0505": "Operational Planner",
        "0506": "Red Team Member",
        "0510": "Basic Information Operations Staff Officer",
        "0520": "Psychological Operations Officer",
        "0530": "Civil Affairs Officer",
        "0540": "Space Operations Staff Officer",
        "0550": "Advanced Information Operations Planner",
        "0602": "Communications Officer",
        "0603": "MAGTF Communications Planner",
        "0605": "Cyber Network Operations Officer",
        "0610": "Telecommunications Systems Engineering Officer",
        "0620": "Space and Waveform Integration Officer",
        "0630": "Network Engineering Officer",
        "0640": "Strategic Electromagnetic Spectrum Officer",
        "0650": "Cyber Network Operations Engineer",
        "0670": "Data Systems Engineering Officer",
        "0802": "Field Artillery Officer",
        "0803": "Target Acquisition Officer",
        "0840": "Naval Surface Fire Support Planner",
        "0919": "Force Fitness Instructor Officer",
        "0930": "Range Officer",
        "0944": "Summer Mountain Leader",
        "0946": "Summer/Winter Mountain Leader",
        "0952": "Formal School Officer Instructor",
        "0953": "Formal School Officer Instructor-Fixed Wing Pilot",
        "0954": "Formal School Officer Instructor-Naval Flight Officer",
        "0955": "Formal School Officer Instructor-Helicopter Pilot",
        "1120": "Utilities Officer",
        "1301": "Basic Combat Engineer Officer",
        "1302": "Combat Engineer Officer",
        "1310": "Engineer Equipment Officer",
        "1330": "Facilities Management Officer",
        "1390": "Bulk Fuel Officer",
        "1701": "Basic Cyberspace Officer",
        "1702": "Cyberspace Officer",
        "1705": "Cyberspace Warfare Development Officer",
        "1706": "Maritime Space Officer",
        "1707": "Influence Officer",
        "1710": "Offensive Cyberspace Warfare Officer",
        "1720": "Defensive Cyberspace Weapons Officer",
        "1801": "Basic Tank and Amphibious Assault Vehicle Officer",
        "1802": "Tank Officer",
        "1803": "Assault Amphibian Officer",
        "2102": "Ordnance Officer",
        "2110": "Ordnance Vehicle Maintenance Officer",
        "2120": "Weapons Repair Officer",
        "2125": "Electro-Optic Instrument Repair Officer",
        "2305": "Explosive Ordnance Disposal Officer",
        "2340": "Ammunition Officer",
        "2602": "Signals Intelligence/Electronic Warfare Officer",
        "2802": "Electronics Maintenance Officer",
        "2805": "Electronics Maintenance Officer Ground",
        "2810": "Telephone Systems Officer",
        "2830": "Ground Radar Maintenance Officer",
        "3002": "Ground Supply Officer",
        "3010": "Ground Supply Operations Officer",
        "3102": "Distribution Management Officer",
        "3302": "Food Service Officer",
        "3402": "Finance Officer",
        "3404": "Financial Management Officer",
        "3408": "Financial Management Resource Officer",
        "3450": "Planning, Programming, Budgeting and Execution Officer",
        "3510": "Motor Transport Maintenance Officer",
        "4130": "Marine Corps Community Services Officer",
        "4302": "Public Affairs Officer",
        "4401": "Student Judge Advocate",
        "4402": "Judge Advocate",
        "4430": "Legal Administrative Officer",
        "4502": "Communication Strategy & Operations Officer",
        "4503": "Visual Information Officer",
        "4602": "Combat Camera Officer",
        "4810": "Recruiting Officer",
        "5502": "Band Officer",
        "5702": "Chemical, Biological, Radiological and Nuclear Defense Officer",
        "5803": "Military Police Officer",
        "5804": "Corrections Officer",
        "5805": "Criminal Investigation Officer",
        "5902": "Electronics Maintenance Officer Aviation Command and Control",
        "5910": "Aviation Radar System Maintenance Officer",
        "5950": "Air Traffic Control Systems Maintenance Officer",
        "5970": "Tactical Data Systems Maintenance Officer",
        "6002": "Aircraft Maintenance Officer",
        "6004": "Aircraft Maintenance Engineer Officer",
        "6044": "Additive Manufacturing Officer",
        "6077": "Weapons and Tactics Instructor",
        "6302": "Avionics Officer",
        "6502": "Aviation Ordnance Officer",
        "6602": "Aviation Supply Officer",
        "6604": "Aviation Supply Operations Officer",
        "6802": "Meteorology and Oceanography Officer",
        "7002": "Expeditionary Airfield and Emergency Services Officer",
        "7202": "Air Command and Control Officer",
        "7204": "Low Altitude Air Defense Officer",
        "7208": "Air Support Control Officer",
        "7210": "Air Defense Control Officer",
        "7220": "Air Traffic Control Officer",
        "7315": "Group 3 UAS MAGTF Officer",
        "7318": "VMU MQ-9 Officer",
        "7380": "Tactical Systems Officer/Mission Specialist",
        "7502": "Forward Air Controller/Air Officer",
        "7509": "Pilot VMA, AV-8B Qualified",
        "7518": "Pilot VMFA, F-35B Qualified",
        "7523": "Pilot VMFA, F/A-18 Qualified",
        "7532": "Pilot VMM, V-22 Qualified",
        "7557": "Pilot VMGR, KC-130 Aircraft Commander",
        "7563": "Pilot HMLA, UH-1Y Qualified",
        "7565": "Pilot HMLA, AH-1 Qualified",
        "7566": "Pilot HMH, CH-53E Qualified",
        "7577": "Weapons and Tactics Instructor",
        "7588": "Naval Flight Officer Qualified EA-6B Electronic Warfare Officer",
        "8001": "Basic Officer",
        "8002": "Joint Terminal Attack Controller",
        "8003": "General Officer",
        "8040": "Colonel, Logistician",
        "8041": "Colonel, Ground",
        "8042": "Colonel, Naval Aviator/Naval Flight Officer",
        "8059": "Aviation Acquisition Management Professional",
        "8060": "Acquisition Specialist",
        "8061": "Acquisition Management Professional",
        "8220": "Political Military Officer",
        "8240": "Basic Foreign Area Officer",
        "8802": "Training and Education Officer",
        "8840": "Manpower Management Officer",
        "8846": "Data Systems Specialist",
        "8858": "Command, Control, Communications, Computers and Intelligence",
        "8878": "Historian",
        "9666": "Space Operations Officer",
        "9701": "Joint Specialty Officer Nominee",
        "9702": "Joint Specialty Officer",
        "9934": "Information Operations Staff Officer",
        "9957": "Acquisition Professional Candidate",
        "9958": "Acquisition Management/Acquisition Core Member",
        "9959": "Acquisition Management Professional",
        "9986": "Joint Terminal Attack Controller",
    },
    "Navy": {
        "CMDCM": "Command Master Chief Petty Officer",
        "FLTCM": "Fleet Command Master Chief Petty Officer",
        "FORCM": "Force Command Master Chief Petty Officer",
    }
}
