CLEARANCES = {
    "C": "Confidential",
    "S": "Secret",
    "TS": "Top Secret",
    "TS/SCI": "Top Secret / Sensitive Compartmented Information",
    "TS/SCI w/ CI Poly": "Top Secret / Sensitive Compartmented Information with Counterintelligence Polygraph",
    "TS/SCI w/ FS Poly": "Top Secret / Sensitive Compartmented Information with Full Scope Polygraph",
}

# source: https://www.defense.gov/Resources/Insignia/
ENLISTED_PAYGRADES = {
    "E-1": {
        "Army": ["Private"],
        "Marine Corps": ["Private"],
        "Navy": ["Seaman Recruit"],
        "Air Force": ["Airman Basic"],
        "Space Force": ["Specialist 1"],
    },
    "E-2": {
        "Army": ["Private"],
        "Marine Corps": ["Private First Class"],
        "Navy": ["Seaman Apprentice"],
        "Air Force": ["Airman"],
        "Space Force": ["Specialist 2"],
    },
    "E-3": {
        "Army": ["Private First Class"],
        "Marine Corps": ["Lance Corporal"],
        "Navy": ["Seaman"],
        "Air Force": ["Airman First Class"],
        "Space Force": ["Specialist 3"],
    },
    "E-4": {
        "Army": ["Corporal", "Specialist"],
        "Marine Corps": ["Corporal"],
        "Navy": ["Petty Officer Third Class"],
        "Air Force": ["Senior Airman"],
        "Space Force": ["Specialist 4"],
    },
    "E-5": {
        "Army": ["Sergeant"],
        "Marine Corps": ["Sergeant"],
        "Navy": ["Petty Officer Second Class"],
        "Air Force": ["Staff Sergeant"],
        "Space Force": ["Sergeant"],
    },
    "E-6": {
        "Army": ["Staff Sergeant"],
        "Marine Corps": ["Staff Sergeant"],
        "Navy": ["Petty Officer First Class"],
        "Air Force": ["Technical Sergeant"],
        "Space Force": ["Technical Sergeant"],
    },
    "E-7": {
        "Army": ["Sergeant First Class"],
        "Marine Corps": ["Gunnery Sergeant"],
        "Navy": ["Chief Petty Officer"],
        "Air Force": ["Master Sergeant", "First Sergeant"],
        "Space Force": ["Master Sergeant"],
    },
    "E-8": {
        "Army": ["Master Sergeant", "First Sergeant"],
        "Marine Corps": ["Master Sergeant", "First Sergeant"],
        "Navy": ["Senior Chief Petty Officer"],
        "Air Force": ["Senior Master Sergeant", "First Sergeant"],
        "Space Force": ["Senior Master Sergeant"],
    },
    "E-9": {
        "Army": ["Sergeant Major", "Command Sergeant Major"],
        "Marine Corps": ["Master Gunnery Sergeant", "Sergeant Major"],
        "Navy": ["Master Chief Petty Officer", "Fleet/Command Master Chief Petty Officer"],
        "Air Force": ["Chief Master Sergeant", "First Sergeant", "Command Chief Master Sergeant"],
        "Space Force": ["Chief Master Sergeant"],
    },
}
WARRANT_OFFICER_PAYGRADES = {
    "W-1": {
        "Army": ["Warrant Officer 1"],
        "Marine Corps": ["Warrant Officer 1"],
        "Navy": ["USN Warrant Officer 1"],
    },
    "W-2": {
        "Army": ["Chief Warrant Officer 2"],
        "Marine Corps": ["Chief Warrant Officer 2"],
        "Navy": ["USN Chief Warrant Officer 2"],
    },
    "W-3": {
        "Army": ["Chief Warrant Officer 3"],
        "Marine Corps": ["Chief Warrant Officer 3"],
        "Navy": ["USN Chief Warrant Officer 3"],
    },
    "W-4": {
        "Army": ["Chief Warrant Officer 4"],
        "Marine Corps": ["Chief Warrant Officer 4"],
        "Navy": ["USN Chief Warrant Officer 4"],
    },
    "W-5": {
        "Army": ["Chief Warrant Officer 5"],
        "Marine Corps": ["Chief Warrant Officer 5"],
        "Navy": ["USN Chief Warrant Officer 5"],
    },
}
OFFICER_PAYGRADES = {
    "O-1": {
        "Army": ["Second Lieutenant"],
        "Marine Corps": ["Second Lieutenant"],
        "Navy": ["Ensign"],
        "Air Force": ["Second Lieutenant"],
        "Space Force": ["Second Lieutenant"],
    },
    "O-2": {
        "Army": ["First Lieutenant"],
        "Marine Corps": ["First Lieutenant"],
        "Navy": ["Lieutenant Junior Grade"],
        "Air Force": ["First Lieutenant"],
        "Space Force": ["First Lieutenant"],
    },
    "O-3": {
        "Army": ["Captain"],
        "Marine Corps": ["Captain"],
        "Navy": ["Lieutenant"],
        "Air Force": ["Captain"],
        "Space Force": ["Captain"],
    },
    "O-4": {
        "Army": ["Major"],
        "Marine Corps": ["Major"],
        "Navy": ["Lieutenant Commander"],
        "Air Force": ["Major"],
        "Space Force": ["Major"],
    },
    "O-5": {
        "Army": ["Lieutenant Colonel"],
        "Marine Corps": ["Lieutenant Colonel"],
        "Navy": ["Commander"],
        "Air Force": ["Lieutenant Colonel"],
        "Space Force": ["Lieutenant Colonel"],
    },
    "O-6": {
        "Army": ["Colonel"],
        "Marine Corps": ["Colonel"],
        "Navy": ["Captain"],
        "Air Force": ["Colonel"],
        "Space Force": ["Colonel"],
    },
    "O-7": {
        "Army": ["Brigadier General"],
        "Marine Corps": ["Brigadier General"],
        "Navy": ["Rear Admiral Lower Half"],
        "Air Force": ["Brigadier General"],
        "Space Force": ["Brigadier General"],
    },
    "O-8": {
        "Army": ["Major General"],
        "Marine Corps": ["Major General"],
        "Navy": ["Rear Admiral Upper Half"],
        "Air Force": ["Major General"],
        "Space Force": ["Major General"],
    },
    "O-9": {
        "Army": ["Lieutenant General"],
        "Marine Corps": ["Lieutenant General"],
        "Navy": ["Vice Admiral"],
        "Air Force": ["Lieutenant General"],
        "Space Force": ["Lieutenant General"],
    },
    "O-10": {
        "Army": ["General"],
        "Marine Corps": ["General"],
        "Navy": ["Admiral"],
        "Air Force": ["General"],
        "Space Force": ["General"],
    },
}
PAYGRADES = {
    **ENLISTED_PAYGRADES,
    **WARRANT_OFFICER_PAYGRADES,
    **OFFICER_PAYGRADES,
}



# sources:
    # https://en.wikipedia.org/wiki/List_of_United_States_Army_careers
ENLISTED_POSITIONS = {
    "Army": {
        "00F": "MOS Immaterial NGB",
        "00G": "MOS Immaterial USAR",
        "00S": "Special Duty Assignment AFSC",
        "00Z": "Command Sergeant Major",
        "09B": "Trainee Unassigned",
        "09C": "Trainee Language",
        "09D": "College Trainee",
        "09G": "ARNG on Active Duty Medical Hold",
        "09H": "USAR on Active Duty Medical Hold",
        "09J": "GED Completion Program",
        "09M": "March 2 Success",
        "09N": "Nurse Corps Candidate",
        "09R": "Simultaneous MBR Program",
        "09S": "Commissioned Officer Candidate",
        "09T": "College Student Army National Guard Officer Program",
        "09U": "Prior Service or Branch Transfer without Defined MOS",
        "09W": "Warrant Officer Candidate",
        "11B": "Infantryman",
        "11C": "Indirect Fire Infantryman",
        "11X": "Undetermined Infantry",
        "11Z": "Infantry Senior Sergeant",
        "12A": "Engineer Senior Sergeant",
        "12B": "Combat Engineer",
        "12C": "Bridge Crewmember",
        "12D": "Diver",
        "12G": "Quarrying Specialist (RC)",
        "12H": "Construction Engineering Supervisor",
        "12K": "Plumber",
        "12M": "Firefighter",
        "12N": "Horizontal Construction Engineer",
        "12P": "Prime Power Production Specialist",
        "12Q": "Power Line Distribution Specialist (RC)",
        "12R": "Interior Electrician",
        "12T": "Technical Engineer",
        "12W": "Carpentry and Masonry Specialist",
        "12X": "General Engineering Supervisor",
        "12Y": "Geospatial Engineer",
        "12Z": "Combat Engineering Senior Sergeant",
        "13B": "Cannon Crewmember",
        "13F": "Fire Support Specialist",
        "13J": "Fire Control Specialist",
        "13M": "MLRS/HIMARS Crewmember",
        "13R": "Field Artillery Firefinder Radar Operator",
        "13T": "Field Artillery Surveyor/Meteorological Crewmember",
        "13U": "Field Artillery Recruit",
        "13Z": "Field Artillery Senior Sergeant/Sergeant Major",
        "14E": "PATRIOT Fire Control Enhanced Operator/Maintainer",
        "14G": "Air Defense Battle Management System Operator",
        "14H": "Air Defense Enhanced Early Warning System Operator",
        "14P": "Air and Missile Defense Crewmember",
        "14S": "Avenger Crew Member",
        "14T": "PATRIOT Launching Station Enhanced Operator/Maintainer",
        "14U": "Air Defense Artillery Recruit",
        "14Z": "Air Defense Artillery (ADA) Senior Sergeant",
        "15B": "Aircraft Powerplant Repairer",
        "15C": "MQ-1 (Gray Eagle) Operator",
        "15D": "Aircraft Powertrain Repairer",
        "15E": "RQ-7 (Shadow) Repairer",
        "15F": "Aircraft Electrician",
        "15G": "Aircraft Structural Repairer",
        "15H": "Aircraft Pneudraulics Repairer",
        "15K": "Aircraft Components Repair Supervisor",
        "15M": "MQ-1 (Gray Eagle) Repairer",
        "15N": "Avionic Mechanic",
        "15P": "Aviation Operations Specialist",
        "15Q": "Air Traffic Control Operator",
        "15R": "AH-64 Attack Helicopter Repairer",
        "15T": "UH-60 Helicopter Repairer",
        "15U": "CH-47 Helicopter Repairer",
        "15V": "Observation/Scout Helicopter Repairer (RC)",
        "15W": "RQ-7 (Shadow) Operator",
        "15X": "AH-64A Armament/Electrical/Avionics Systems Repairer",
        "15Y": "AH-64D Armament/Electrical/Avionic Systems Repairer",
        "15Z": "Aircraft Maintenance Senior Sergeant",
        "17C": "Cyber Operations Specialist",
        "17E": "Electronic Warfare Specialist",
        "17Z": "Cyberspace and Electromagnetic Activities (CEMA) Senior Sergeant",
        "18B": "Special Forces Weapons Sergeant - SGT-SFC",
        "18C": "Special Forces Engineer Sergeant - SGT-SFC",
        "18D": "Special Forces Medical Sergeant - SGT-SFC",
        "18E": "Special Forces Communications Sergeant - SGT-SFC",
        "18F": "Special Forces Intelligence Sergeant - SSG-SFC",
        "18X": "Special Forces Candidate",
        "18Z": "Special Forces Senior Sergeant - MSG-CSM",
        "25B": "Information Technology Specialist",
        "25D": "Cyber Network Defender",
        "25E": "Electromagnetic Spectrum Manager",
        "25H": "Network Communication Systems Specialist",
        "25S": "Satellite Communications Systems Operator/Maintainer",
        "25U": "Signal Support Systems Specialist",
        "25W": "Telecommunications Operations Chief",
        "25X": "Chief Signal NCO",
        "25Z": "Visual Information Operations Chief",
        "27D": "Paralegal Specialist",
        "31B": "Military Police",
        "31D": "CID Special Agent",
        "31E": "Internment/Resettlement Specialist",
        "31K": "Working Dog Handler",
        "31Z": "Military Police Senior Sergeant",
        "09L": "Interpreter/Translator",
        "35F": "Intelligence Analyst",
        "35G": "Geospatial Intelligence Imagery Analyst",
        "35L": "Counterintelligence Special Agent",
        "35M": "Human Intelligence Collector",
        "35N": "Signals Intelligence Analyst",
        "35P": "Cryptologic Linguist",
        "35S": "Signals Collector/Analyst",
        "35T": "Military Intelligence Systems Maintainer/Integrator",
        "35V": "Signals Intelligence Senior Sergeant/Chief Signals Intelligence Sergeant",
        "35X": "Intelligence Senior Sergeant/Chief Intelligence Sergeant",
        "35Y": "Chief Counterintelligence/Human Intelligence Sergeant",
        "35Z": "Signals Intelligence (Electronic Warfare) / Senior Sergeant/ Chief",
        "36B": "Financial Management Technician",
        "37F": "Psychological Operations Specialist",
        "38B": "Civil Affairs Specialist",
        "38R": "Civil Reconnaissance Sergeant",
        "38W": "Civil Affairs Medic",
        "38Z": "Civil Affairs Senior Sergeant",
        "42A": "Human Resources Specialist",
        "42R": "Musician",
        "42S": "Special Band Member",
        "46T": "Visual Information Equipment Operator-Maintainer",
        "46S": "Public Affairs Mass Communications Specialist",
        "46V": "Visual Information Specialist",
        "46Z": "Chief Public Affairs NCO",
        "68A": "Biomedical Equipment Specialist",
        "68B": "Orthopedic Specialist",
        "68C": "Practical Nursing Specialist-(LPN/LVN)",
        "68D": "Operating Room Specialist",
        "68E": "Dental Specialist",
        "68F": "Physical Therapy Specialist",
        "68G": "Patient Administration Specialist ",
        "68H": "Optical Laboratory Specialist",
        "68J": "Medical Logistics Specialist",
        "68K": "Medical Laboratory Specialist",
        "68L": "Occupational Therapy Specialist",
        "68M": "Nutrition Care Specialist",
        "68N": "Cardiovascular Specialist ( Discontinued)",
        "68P": "Radiology Specialist",
        "68Q": "Pharmacy Specialist",
        "68R": "Veterinary Food Inspection Specialist",
        "68S": "Preventive Medicine Specialist",
        "68T": "Animal Care Specialist",
        "68U": "Ear, Nose, and Throat (ENT) Specialist (Discontinued)",
        "68V": "Respiratory Specialist",
        "68W": "Combat Medic Specialist",
        "68X": "Behavioral Health Specialist",
        "68Y": "Eye Specialist",
        "68Z": "Chief Medical NCO",
        "74D": "Chemical, Biological, Radiological and Nuclear (CBRN) Specialist",
        "88H": "Cargo Specialist",
        "88K": "Watercraft Operator",
        "88L": "Watercraft Engineer",
        "88M": "Motor Transport Operator",
        "88N": "Transportation Management Coordinator",
        "88P": "Railway Equipment Repairer (RC)",
        "88T": "Railway Section Repairer (RC)",
        "88U": "Railway Operations Crew Member (RC)",
        "88Z": "Transportation Senior Sergeant",
        "89A": "Ammunition Stock Control and Accounting Specialist",
        "89B": "Ammunition Specialist",
        "89D": "Explosive Ordnance Disposal Specialist",
        "91A": "M1 Abrams Tank System Maintainer ",
        "91B": "Wheeled Vehicle Mechanic ",
        "91C": "Utilities Equipment Repairer ",
        "91D": "Power Generation Equipment Repairer ",
        "91E": "Allied Trades Specialist ",
        "91F": "Small Arms/Towed Artillery Repairer ",
        "91G": "Fire Control Repairer ",
        "91H": "Track Vehicle Repairer ",
        "91J": "Quartermaster and Chemical Equipment Repairer ",
        "91L": "Construction Equipment Repairer ",
        "91M": "Bradley Fighting Vehicle System Maintainer ",
        "91P": "Self Propelled Artillery Systems Maintainer ",
        "91S": "Stryker Systems Maintainer",
        "91X": "Maintenance Supervisor ",
        "91Z": "Senior Maintenance Supervisor ",
        "94A": "Land Combat Electronic Missile System Repairer ",
        "94D": "Air Traffic Control Equipment Repairer",
        "94E": "Radio & Communications Security (COMSEC) Equipment Repairer",
        "94F": "Computer/Detection Systems Repairer",
        "94H": "Test Measurement and Diagnostic Equipment (TMDE) Maintenance Support Specialist",
        "94M": "Radar Repairer",
        "94P": "Multiple Launch Rocket System (MLRS) Repairer ",
        "94R": "Avionic and Survivability Repairer",
        "94S": "PATRIOT System Repairer",
        "94T": "AVENGER System Repairer",
        "94W": "Electronic Maintenance Chief",
        "94X": "Senior Missile Systems Maintainer",
        "94Y": "Integrated Family of Test Equipment (IFTE) Operator/Maintainer",
        "94Z": "Senior Electronic Maintenance Chief",
        "92A": "Automated Logistical Specialist",
        "92F": "Petroleum Supply Specialist",
        "92G": "Culinary Specialist",
        "92L": "Petroleum Laboratory Specialist",
        "92M": "Mortuary Affairs Specialist",
        "92R": "Parachute Rigger",
        "92S": "Shower/Laundry and Clothing Repair Specialist",
        "92W": "Water Treatment Specialist",
        "92Y": "Unit Supply Specialist",
        "92Z": "Senior Noncommissioned Logistician",
    },
    "Navy": {
        "ok": "ok",
    }
}
